CREATE TABLE STUDENT(
ID INTEGER NOT NULL AUTO_INCREMENT,
STU_USERNAME VARCHAR(20) NOT NULL,
STU_PASSWORD VARCHAR(80) NOT NULL,
EMAIL VARCHAR(80) NOT NULL,

PRIMARY KEY (ID)

);
CREATE TABLE STUDENT_INFO(
ID_STU_INFO INTEGER NOT NULL AUTO_INCREMENT,
FIRSTNAME VARCHAR(80) NOT NULL,
LASTNAME VARCHAR(80) NOT NULL,
FACULTY VARCHAR(80) NOT NULL,
DEGREE VARCHAR(80),
WORK_EXPERIENCE VARCHAR(80),
SKILL VARCHAR(80),
LANGUAGE_SKILL VARCHAR(80),
REF_STUDENT INTEGER NOT NULL,
FOREIGN KEY (REF_STUDENT) REFERENCES STUDENT(ID),
PRIMARY KEY (ID_STU_INFO)
);



CREATE TABLE COMPANY(
ID_COMP INTEGER NOT NULL AUTO_INCREMENT,
COMP_USERNAME VARCHAR(20) NOT NULL,
COMP_PASSWORD VARCHAR(80) NOT NULL,
COMPANY_NAME VARCHAR(20) NOT NULL,
LOCATION VARCHAR(80) NOT NULL,
CONTACT VARCHAR(80),
PRIMARY KEY (ID_COMP)
);




CREATE TABLE ADVERTISEMENT(
ID_ADV INTEGER NOT NULL AUTO_INCREMENT,
DATE_OF_PUBLISH DATE NOT NULL,
TITLE VARCHAR(80) NOT NULL,
DEADLINE DATE NOT NULL,
CONTACT VARCHAR(80) NOT NULL,
REQUIREMENT TEXT NOT NULL,
FURTHER_INFO TEXT,
NUMBER_OF_VACCANCIES INTEGER,
REF_COMP INTEGER NOT NULL,
PRIMARY KEY (ID_ADV),

FOREIGN KEY (REF_COMP) REFERENCES COMPANY (ID_COMP)
);
